### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by tbodt** [caniusepython3/caniusepython3.com#56]
If you try to check python 3 compatibility of anything right now, you get a 500 internal server error.

**Comment by tricoder42** [comment]
The problem is resolved. I also set up synthetic check for search, so next time I'm notified if anything like this happens again.

Thank you for report! 👍

**Comment by bobsbeenjamin** [comment]
Is this issue back?
![image](https://user-images.githubusercontent.com/3780939/73568784-555fa900-4426-11ea-83d0-d8d5877145e1.png)

**Comment by tricoder42** [comment]
Maybe temporary? Seems to be up right now.

**Comment by bobsbeenjamin** [comment]
> Maybe temporary? Seems to be up right now.

I'm still getting the error. Is there something wrong with my `requirements.txt` file?

```
# This was converted from environment.yml, for use on https://caniusepython3.com/

anaconda
conda-forge
pyqt
PyOpenGL
PyOpenGL-accelerate
numpy
Pillow
nose
requests
flask
future
werkzeug
iso8601
keyring
numba
gevent
gdal
pytz
scikit-image
boto3
nose2
piexif
requests_toolbelt
python-dateutil
easydict
pytest-qt
keyboard
```
